### ISSUE TITLE
Case sensitivity for columns names can cause errors during ingest process

### ISSUE THREAD

**Issue by bpstewar** [worldbank/DECAT_Space2Stats#100]
**Describe the bug**
When ingesting data to the development server, I encounter an error after the data appear to have been processed

**To Reproduce**
1. Install new Anaconda environment
2. Poetry install s2s --with docs
3. Generate STAC metadata
4. space2stats-ingest "postgresql://USER:PASSWORD@sullenly-godlike-turbot.data-1.use1.tembo.io:5432/postgres" "C:\WBG\Work\Code\DECAT_Space2Stats\space2stats_api\src\space2stats_ingest\METADATA\stac\space2stats-collection\urbanization_ghssmod\urbanization_ghssmod.json" "C:\WBG\Work\S2S\ingest\GHS_SMOD_Counts_and_Pop.parquet"

**Expected behavior**
```
(s2s) PS C:\WBG\Work\Code\DECAT_Space2Stats\space2stats_api\src> space2stats-ingest "postgresql://USER:PASSWORD@sullenly-godlike-turbot.data-1.use1.tembo.io:5432/postgres" "C:\WBG\Work\Code\DECAT_Space2Stats\space2stats_api\src\space2stats_ingest\METADATA\stac\space2stats-collection\urbanization_ghssmod\urbanization_ghssmod.json" "C:\WBG\Work\S2S\ingest\GHS_SMOD_Counts_and_Pop.parquet"
Loading data into PostgreSQL database from C:\WBG\Work\S2S\ingest\GHS_SMOD_Counts_and_Pop.parquet
Ingesting Temporary Table: 100%|█████████████████████████████████████████████| 14117882/14117882 [02:21<00:00, 99509.52rows/s]
Adding new columns: ['GHS_11_count', 'GHS_12_count', 'GHS_13_count', 'GHS_21_count', 'GHS_22_count', 'GHS_23_count', 'GHS_30_count', 'GHS_Total_Count', 'GHS_11_pop', 'GHS_12_pop', 'GHS_13_pop', 'GHS_21_pop', 'GHS_22_pop', 'GHS_23_pop', 'GHS_30_pop', 'GHS_Total_Pop']...
Adding columns to dataset... All or nothing operation may take some time.
An error occurred during update. Rolling back changes.
An unexpected error occurred: INVALID_STATE: [Driver Manager] AdbcConnectionRollback: must call AdbcConnectionNew first
```
The command above looks like it works well; the temporary table uploads correctly. However, after the new columns are identified, the AdbcConnectionRollback error occurs, and I cannot understand it

**Desktop (please complete the following information):**
 - OS: World Bank Windows machine

**Comment by zacdezgeo** [comment]
I was able to reproduce the issue with the following test: https://github.com/worldbank/DECAT_Space2Stats/compare/main...bug/case-sensitivity

**Comment by zacdezgeo** [comment]
Changes I am planning on implementing to address this:
1. All column names in the Parquet file are converted to lowercase before processing.
2. All column names in the STAC metadata are converted to lowercase for consistency.
3. Database column names are treated as lowercase when verifying or adding them.
