### ISSUE TITLE
Add ReviewNB to facilitate notebook reviews in PRs

### ISSUE THREAD

**Issue by zacdezgeo** [worldbank/DECAT_Space2Stats#103]
We use [ReviewNB](https://app.reviewnb.com/) in many other projects. It's great to provide a more collaborative experience for notebook reviews. I am unable to add it to this repository. @bpstewar @andresfchamorro; could you try from your end? You likely have more permissions than I do.

**Comment by andresfchamorro** [comment]
I just tried and can see the repo in the app, but can you see it?

**Comment by zacdezgeo** [comment]
Thanks @bpstewar! I added a blank commit to #102 to test it out. The integration worked, you can see the comment directly on the PR.
