### ISSUE TITLE
Metadata support/discussion

### ISSUE THREAD

**Issue by bpstewar** [worldbank/DECAT_Space2Stats#11]
Andres will be leading the work designing the metadata catalog, I wanted to open this issue to discuss how metadata will be stored and formatted.

I would look to the World Bank Data python library for examples of how metadata can be effectively search and formatted: https://pypi.org/project/world-bank-data/

**Comment by andresfchamorro** [comment]
Closing as it's a duplicate of https://github.com/worldbank/DECAT_Space2Stats/issues/15
