### ISSUE TITLE
Metadata needs research

### ISSUE THREAD

**Issue by zacharyDez** [worldbank/DECAT_Space2Stats#15]
As discussed, it would be critical to document the WB's metadata needs to see how we incorporate more advanced querying within the space2stats API.

@bpstewar @andresfchamorro; do you have a timeline for this?

**Comment by zacharyDez** [comment]
@bpstewar @andresfchamorro; keep me updated based on feedback from @mah0001. As discussed, as long as the attribute names match does of the API to access the data, the user flow of querying for the desired fields and retrieving the data can be decoupled.

**Comment by zacharyDez** [comment]
@andresfchamorro; any updates on the metadata side?

**Comment by andresfchamorro** [comment]
@zacharyDez, @bpstewar 

Here is a first stab at our metadata STAC file: https://github.com/worldbank/DECAT_Space2Stats/tree/metadata/notebooks/METADATA

I used the notebook following a pystac tutorial to create `catalog.json`, and then the main item/assets. I am managing the content through an Excel spreadsheet but grateful if you can advise here on best practices.

I also created a copy to see how it would look with stac browser: https://radiantearth.github.io/stac-browser/#/external/andresfchamorro.github.io/test-stac/stac/catalog.json?.language=en

As discussed, it would be great if we can expand the API to allow for queries on the metadata. Users should be able to get a list of topics/sources, and variables available per topic. Based on this need, could you provide a recommendation for how to implement this and we can set a time to discuss next steps?

Thanks!
