### ISSUE TITLE
add CDK requirements and deployment Readme

### ISSUE THREAD

**Issue by vincentsarago** [worldbank/DECAT_Space2Stats#40]
right now there are no requirement (python and nodes) for our CDK code

https://github.com/worldbank/DECAT_Space2Stats/tree/main/space2stats_api/cdk

[package.json](https://github.com/user-attachments/files/16817051/package.json)
[requirements-cdk.txt](https://github.com/user-attachments/files/16817043/requirements-cdk.txt)

A Readme about how to deploy won't be a bad idea as well 

[README.md](https://github.com/user-attachments/files/16817055/README.md)

**Comment by zacharyDez** [comment]
@vincentsarago; I'm a little confused about where we should put the `package.json` and `requirements-cdk.txt`. Wouldn't the requirements already be covered in our `pyproject.toml`? 

sharing some information about my system in case it helps:
```
cdk --version                  
2.150.0 (build 3f93027)
node --version                 
v20.15.1
```

**Comment by vincentsarago** [comment]
the requirement for the CDK shouldn't be in the pyproject.toml

the files should live in https://github.com/worldbank/DECAT_Space2Stats/tree/main/space2stats_api/cdk

> sharing some information about my system in case it helps:

yeah, cdk has the habit of breaking things ofter which is why it's better to have `pinned` dependencies and use virtual env (https://github.com/developmentseed/eoapi-devseed?tab=readme-ov-file#deployment)
