### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by zacharyDez** [worldbank/DECAT_Space2Stats#51]
### Problem Description

Currently, there are no standardized tests to verify that the API handles errors gracefully. We need to ensure proper error handling in edge cases and provide informative messages for users. 

For example, when we query the `summary` endpoint with an invalid field, here is the message we receive:
```
Exception: Failed to get summary: {"detail":[{"type":"list_type","loc":["body","fields"],"msg":"Input should be a valid list","input":null}]}
```

It's not as descriptive as:
```
Exception: Invalid field used [field name]
```

### Expected Behavior

Implement error handling for the following cases:

- Querying with an invalid hex ID.
- Requesting a non-existent field.
- Sending a malformed request.

The API should return appropriate error codes (e.g., 400 Bad Request, 404 Not Found) and clear error messages for each scenario to guide users in correcting their requests.

**Comment by zacharyDez** [comment]
@vincentsarago, you talked previously about introducing an `error.py` file. Can you provide a reference example here?

**Comment by vincentsarago** [comment]
> Can you provide a reference example here?

Basically you want to add an error handler which will recognize input errors and translate to correct HTTP Status error 

see: https://github.com/developmentseed/tipg/blob/main/tipg/errors.py
