### ISSUE TITLE
Add aggregation endpoint

### ISSUE THREAD

**Issue by zacharyDez** [worldbank/DECAT_Space2Stats#57]
Some WB end-users would like an aggregated result for their input polygon. 

We will start with an example and be open to feedback.

**Comment by andresfchamorro** [comment]
@zacharyDez @bpstewar 

Here is the example I was playing around with: https://github.com/worldbank/DECAT_Space2Stats/blob/notebooks/notebooks/API/api_population_use_case.ipynb

What I envision is a function that takes in a GeoDataFrame, a list of API fields, and a method for aggregation. It could cover the following:
1. Run the necessary requests per AOIs (efficiently?)
2. Handle duplicate hex ids (one way could be to assign an h3 cell to the admin area with the largest overlap)
3. Summarize by area (sum, mean, median, maybe even weighted mean)
4. Return same GeoDataFrame with summary stats

**Comment by zacharyDez** [comment]
Ok, let's discuss together! Opened a draft PR (#59) with an aggregation example. I have a few concerns that we can address there.

**Comment by zacharyDez** [comment]
After discussion, we want to support an aggregation endpoint that has the following details:
- Returns a single row
- Can filter on min and max values
- Supports some classic value aggregation functions (sum, mean, median, max, min)
