### ISSUE TITLE
gh actions for gh-pages not working

### ISSUE THREAD

**Issue by andresfchamorro** [worldbank/DECAT_Space2Stats#90]
**Describe the bug**
The github actions workflow inherited from our template is not working. It is supposed to run once a branch is merged but it's failing due to a dependency issue with sphinx: https://github.com/worldbank/DECAT_Space2Stats/actions/runs/11775814066/job/32796972085

Potential fix: Add required package to docs/requirements.txt

*Note: these are the dependencies to build the gh-pages site, not for the package/api.*

Additionally, could we explore a way to automatically copy the stac from main into the gh-pages branch as part of this action / or a new action? That way we can feed it to radiant earth stac browser: https://radiantearth.github.io/stac-browser/#/external/worldbank.github.io/DECAT_Space2Stats/stac/catalog.json

Previously, I added it manually but it gets deleted with the current action setup.

**Comment by bpstewar** [comment]
The error is being caused by a Sphinx dependancy that I added to the gh-pages _config.yml- it can be removed  as it isn't working anyway.

**Comment by Gabe-Levin** [comment]
Successfully deployed the latest changes from pages_update branch using, `ghp-import -n -p -f _build/html`.
