### ISSUE TITLE
Update h3ronpy to release when available

### ISSUE THREAD

**Issue by zacdezgeo** [worldbank/DECAT_Space2Stats#93]
The newest release of h3ronpy hasn't been made available. We point to a pre-built wheel on s3 at the moment. We should plan to use the release when available.

**Comment by zacharyDez** [comment]
The custom wheels available on S3 only match Linux and certain Mac builds. Users on other builds can't install h3ronpy, which causes issues running ingestion workflows and running space2stats with the Python library.
